services:
  mongodb:
    image: londonfire.azurecr.io/mongo-londonfire:latest
    # command: ["mongod", "--dbpath=/dbdata", "--bind_ip", "0.0.0.0"]
    # env_file: ./.env.production
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    #   - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    #   - MONGO_LONDON_FIRE_USER=${MONGO_LONDON_FIRE_USER}
    #   - MONGO_LONDON_FIRE_PASSWORD=${MONGO_LONDON_FIRE_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '0.1'
    restart: always
    volumes:
      - londonfire:/dbdata
    networks:
      - stack

  api:
    image: londonfire.azurecr.io/api:latest
    # env_file: ./.env.production
    ports:
      - "8000:8000"
    # environment:
    #   - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN}
    #   - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
    #   - JWT_ALGORITHM=${JWT_ALGORITHM}
    #   - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    #   - DATABASE_URL=${DATABASE_URL}
    #   - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - londonfiremodele:/data/modele
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.1'
    networks:
      - stack
    depends_on:
      - mongodb
  
  entrainementmodel:
    image: londonfire.azurecr.io/entrainement_model:latest
    # env_file: ./.env.production
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    #   - VISUAL_CROSSING_KEY=${VISUAL_CROSSING_KEY}
    #   - SELENIUM_HOST=${SELENIUM_HOST}
    volumes:
      - londonfiremodele:/data/modele
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.1'
    networks:
      - stack
    depends_on:
      - mongodb
      - selenium
  
  selenium:
    image: selenium/standalone-chrome:108.0
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.1'
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=30
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_VNC_NO_PASSWORD=1
    networks:
      - stack

networks:
  stack:
    driver: bridge

volumes:
  londonfire:
    driver: azure_file
    driver_opts:
        share_name: londonfire
        storage_account_name: londonfire

  londonfiremodele:
    driver: azure_file
    driver_opts:
        share_name: londonfiremodele
        storage_account_name: londonfire
