name: deploy-prod

on:
  push:
    branches: [ ScriptInitMongoDB ]

jobs:
  test:
    env:
      DATABASE_URL: mongodb://localhost:27017/test?retryWrites=true&w=majority
      MONGO_INITDB_DATABASE: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: "4.2"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
        restore-keys: | 
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest fastapi uvicorn pymongo httpx wheel python-dotenv numpy pandas
    - name: Run pytest
      run: | 
        pytest api/tests/
